import GridGallery from '@/components/GridGallery'
import HomepageHeroSection from '@/components/HomepageHeroSection'
import PageWrapper from '@/components/PageWrapper'

export const metadata = {
  title: 'Homepage',
  description: 'Generated by create next app',
  keywords: 'homepage',
}

export default function Home() {
  return (
    <>
      <PageWrapper>
        <HomepageHeroSection />
      </PageWrapper>
      <GridGallery />
    </>
  )
}
