import '@/assets/css/base.css'
import Header from '@/components/Header/Header'

export const metadata = {
  title: 'bobo',
  description: 'Generated by create next app',
  keywords: 'too',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
