import '@/assets/css/base.css'

export const metadata = {
  title: 'bobo',
  description: 'Generated by create next app',
  keywords: 'too',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
